### PR TITLE
Add support for Linux 4.12

### LINKED ISSUE #153: next-20170501, aka 4.12: build failure due to changes in mac80211
Flags like RX_FLAG_HT are no longer.

hif/pcie/rx.c:231:19: error: 'RX_FLAG_HT' undeclared (first use in this function)
   status->flag |= RX_FLAG_HT;
                         ^

### PR DESCRIPTION
**Pull request by seragh**
The relevant commitns made it into mainline by now.

Tested on Linux next-20170503 (with tampered LINUX_VERSION_CODE), up for a little over 20h without hiccups.

Fixes #153

### CODE REVIEW

**Comment by yuhhaurlin** [comment]
I think we can't use linux version checking for this driver. I will check  how to support it later. Thanks.

**Comment by seragh** [comment]
On Thu, 04 May 2017 19:28:30 -0700
yuhhaurlin <notifications@github.com> wrote:

> I think we can't use linux version checking for this driver. I will
> check  how to support it later. Thanks.
> 

Ok, let us employ a hack then.

Compile tested the amended commit on v4.11 and next-20170504.

**Comment by yuhhaurlin** [comment]
It looks like we can check if RX_FLAG_HT is defined. If not, just define is as RX_ENC_HT. Same as RX_ENC_VHT.

**Comment by yuhhaurlin** [comment]
Sorry. A lot of missing constants. I merge this PR. Thanks.

**Pull request merged**
