### PR TITLE
Stability Improvements

### PR DESCRIPTION
**Pull request by thagabe**
This PR contains two commit with stability improvements for WRT3200ACM and WRT1900ACv1. 

Tested on both platforms. 

Signed-off: Gabe Rodriguez <lifehacksback@gmail.com>

### CODE REVIEW

**Comment by BrainSlayer** [comment]
merged to dd-wrt too

**Comment by tapper82** [comment]
@BrainSlayer  Hi if you get time can you post back and let us know how it goes in DDWrt pleas? Thanks

**Comment by BrainSlayer** [comment]
yes. just need some days to aggregate the feedback from users.

**Comment by anomeome** [comment]
Was a later 88W8864 OEM image checked for a more recent BLOB; i.e. ACS V2 2020/5/1.

**Comment by BrainSlayer** [comment]
i checked the latest firmware 2020/5/1 but the included firmware blob is identical with the older ones. nothing new inside

**Comment by BrainSlayer** [comment]
> @BrainSlayer Hi if you get time can you post back and let us know how it goes in DDWrt pleas? Thanks

one user complained yesterday that he is unable to connect anymore with this change. no further info yet

**Comment by thagabe** [comment]
@BrainSlayer Any updates? I'm running this on my OpenWRT router for *46d 23h 21m 39s* and I have not experienced any issues on any wireless devices.

**Comment by BrainSlayer** [comment]
> @BrainSlayer Any updates? I'm running this on my OpenWRT router for _46d 23h 21m 39s_ and I have not experienced any issues on any wireless devices.

i just can quote reports from users. once i enabled it he had problems with connecting to his ap with his client. this may not apply to all clients .but i dont have further info.

**Comment by eduperez** [comment]
Some users at OpenWrt's forum also reported connecting issues with this patch; I tried to convince them to come here, but I have no further info.

**Comment by stklcode** [comment]
I'm none of the mentioned users, but nevertheless I installed the 93c3d8d packages on my WRT1900ACSv1 running OpenWRT 19.07.4 and experienced issues similar to the ones reported on the forums..

After installing the packages and rebooting the router, several clients refuse to connect. Rebooted two of them (one Android 11, one iPadOS 14.2) without any change. There are some clients that seem to work fine (at least one Fedora Linux machine with Intel WiFi).

Apparently both radios are affected.
Running in AC/N mode, fixed channels, WPA2-PSK/WPA3-SAE mixed with optional 802.11w, both with 3 pairwise identically configured networks.


<details><summary>Kernel log extract</summary>

> kernel: ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
> kernel: ieee80211 phy0: return code: 0x1122
> kernel: ieee80211 phy0: timeout: 0x1122
> kernel: wlan0-1: failed to remove key (0, xx:xx:xx:xx:xx:xx) from hardware (-5)
> kernel: ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy0: cmd 0x9125=BAStream timed out
> kernel: ieee80211 phy0: return code: 0x1125
> kernel: ieee80211 phy0: timeout: 0x1125
> kernel: ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy0: cmd 0x9111=SetNewStation timed out
> kernel: ieee80211 phy0: return code: 0x1111
> kernel: ieee80211 phy0: timeout: 0x1111
> kernel: ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
> kernel: ieee80211 phy0: return code: 0x1122
> kernel: ieee80211 phy0: timeout: 0x1122
> kernel: wlan0-2: failed to remove key (0, yy:yy:yy:yy:yy:yy) from hardware (-5)
> kernel: ieee80211 phy0: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy0: cmd 0x9122=UpdateEncryption timed out
> kernel: ieee80211 phy0: return code: 0x1122
> kernel: ieee80211 phy0: timeout: 0x1122
> kernel: wlan0: failed to remove key (0, zz:zz:zz:zz:zz:zz) from hardware (-5)
> kernel: ieee80211 phy1: MACREG_REG_INT_CODE: 0x0000
> kernel: ieee80211 phy1: cmd 0x9122=UpdateEncryption timed out
> kernel: ieee80211 phy1: return code: 0x1122
> kernel: ieee80211 phy1: timeout: 0x1122
> kernel: wlan1: failed to remove key (0, zz:zz:zz:zz:zz:zz) from hardware (-5)

</details>

<details><summary>Configuration extract</summary>
<pre>
config wifi-device 'radio0'
	option type 'mac80211'
	option hwmode '11a'
	option distance '8'
	option htmode 'VHT80'
	option country 'DE'
	option channel '36'
	option legacy_rates '0'
	option path 'soc/soc:pcie/pci0000:00/0000:00:01.0/0000:01:00.0'
config wifi-device 'radio1'
	option type 'mac80211'
	option channel '11'
	option hwmode '11g'
	option country 'DE'
	option distance '8'
	option htmode 'HT40'
	option legacy_rates '0'
	option path 'soc/soc:pcie/pci0000:00/0000:00:02.0/0000:02:00.0'
config wifi-iface 'wifinet0'
	option device 'radio0'
	option mode 'ap'
	option ssid '*****'
	option key '*****'
	option disassoc_low_ack '0'
	option macaddr '**:**:**:**:**:**'
	option network '*****'
	option encryption 'sae-mixed'
	option ieee80211w '1'
	option macfilter 'allow'
	list maclist '**:**:**:**:**:**'
config wifi-iface 'wifinet1'
	option device 'radio1'
	option mode 'ap'
	option ssid '*****'
	option key ' '*****''
	option macfilter 'allow'
	option disassoc_low_ack '0'
	option macaddr '**:**:**:**:**:**'
	option network '*****'
	option encryption 'sae-mixed'
	option ieee80211w '1'
	list maclist '**:**:**:**:**:**'
config wifi-iface 'wifinet2'
	option device 'radio0'
	option mode 'ap'
	option ssid '*****'
	option key '*****'
	option network '*****'
	option isolate '1'
	option auth_cache '1'
	option ieee80211w '1'
	option encryption 'sae-mixed'
[...]
</pre>
</details>

**Comment by thagabe** [comment]
> WRT1900ACS

If I am not mistaken the ACS runs a different firmware than the 1900AC v1 so that change shouldn't affect your device. The only other option is that possibly the changes are only meant for the 3200ACM. I'll see if I can rewrite the patches to be target specific.

**Comment by stklcode** [comment]
I’m aware of the difference. But the package by @eduperez are the same (double checked I loaded the correct files) and they did affect, i.e. broke my device. Reverting back to the previously installed firmware immediately solved the issue.

I did not investigate if the patch or the packaging is suboptimal in this place.

**Comment by BrainSlayer** [comment]
> > WRT1900ACS
> 
> If I am not mistaken the ACS runs a different firmware than the 1900AC v1 so that change shouldn't affect your device. The only other option is that possibly the changes are only meant for the 3200ACM. I'll see if I can rewrite the patches to be target specific.

all 1900/1200 series etc. are running the same firmware and contain the same wifi chipset. only the wrt3200 is different

**Pull request closed without merging**
