### PR TITLE
Add support for WPS IE

### PR DESCRIPTION
**Pull request by hdiniz**
Signed-off-by: Henrique Diniz <hdiniz@outlook.com>

### CODE REVIEW

**Comment by hdiniz** [comment]
Please consider integrating support for WPS IE.
Regards.

**Comment by yuhhaurlin** [comment]
@hdiniz Had you done the tested for this modification?

**Comment by hdiniz** [comment]
Yes, this modification effectively adds WPS IE to beacon, probes, etc..
The rest is handled by hostapd. It's working! :)

In fact I also added other IEs, for hotspot 2.0 and interworking. Also worked just fine. I wonder if you would accept those as well...

For what I understood ie_proprietary_list has a maximum size, so maybe that could be a limitation. Please give your thoughts on this.

Regards .

**Comment by yuhhaurlin** [comment]
Yes,  Length is what I worry. I think I will check WPS first. If it is all right, I will accept the code. Thanks.

**Comment by hdiniz** [comment]
please note that I made a typo while preparing the commit for submission, sorry about that

**Comment by yuhhaurlin** [comment]
Sorry, it is not a correct way to set WPS IE here. I will close it and I will update correct code later.

**Comment by chinawrj** [comment]
@hdiniz @yuhhaurlin 
Actually this patch works well with WPS with latest hostapd under WPS-PBC/WPS-PINCODE. I am wandering maybe there is another way to add WPS IE for WPS support? BTW, also I concern about the max length of ie_list_len_proprietary

**Comment by hdiniz** [comment]
@chinawrj Yes, I tested and this works. Though there might be another way to implement according to @yuhhaurlin. Maybe the problem is the length...

@yuhhaurlin For my use case this method is fine for the moment. If you implement this different I will be glad to help you test it.

**Pull request closed without merging**
