### PR TITLE
Properly detect Linux/Backports version

### PR DESCRIPTION
**Pull request by jeolives**
Fixes ("747796b"): Fixed driver loading with kernel 5.3+

Signed-off-by: Jose Olivera <oliverajeo@gmail.com>

### CODE REVIEW

**Comment by jeolives** [comment]
I'm not sure if this will work @kaloz @borkra 

I can't test this at the moment so please advise me if this actually fixes it.

**Comment by 1Jeff1** [comment]
@jeolives Thi s is my fix https://github.com/1Jeff1/mwlwifi/commit/4cf1a9280a1059445aab8f8a57fe6780df7dbbd5

**Comment by borkra** [comment]
This fix going to break compilation with the kernel prior to version 5.3, when backports are not used

**Comment by borkra** [comment]
@jeolive  This change goin to not work if backported Wi-Fi stack is older then 5.3, like pubished OpenWRT release 19.0x or 17.0x

**Comment by lucenera** [comment]
@jeolives Everything worked as expected on the master. Thanks again. Now the best router ever is even better.

**Comment by 1Jeff1** [comment]
> @1Jeff1 This fix going to break compilation with the kernel prior to version 5.3, when backports are not used

Well actually not, as you can add a patch on OpenWrt to drop policy vendor patch.

**Comment by borkra** [comment]
@1Jeff1 you are missing the case of compiling this driver directly inside older kernels. OpenWRT does not do that but others do.

With code as it is right now mwlwifi will compile with any kernel supported without patches. 

And backported implementations require patches.

Isn’t it better then have git version compiled only with unreleased version software?

**Comment by jeolives** [comment]
Well, I'm at a wits end if there's no macro for backports detection.

@borkra The workaround is to just patch `mwlwifi` on the OpenWrt master branch to get rid of the checks (at least until `mvebu` gets kernel 5.4) as per the [updated PR](https://github.com/openwrt/openwrt/pull/2756/commits/f05311a4d07bf3490bc443b6f89fa9783b026abb).

This will make it easy to backport to 19.07 / 18.06 / 17.01 or whatever as one would just have update the date, commit ID, and package hash. Though, I don't know why you'd do that for anything past 19.07.

I do not agree with the patching backports approach. The maintainers will instantly shoot this down as a maintenance headache for a single out of tree driver. Whilst backports has a lot of patches, it is for patches that are for **in-tree** drivers. An example of this, is that there are no patches for ath10k-ct in the mac80211 folder.

**Comment by borkra** [comment]
Well, it seems you misunderstood. 

I believe, the driver out of mwlwifi tree should be able to compile without any patches with any kernel (when no backports used).
OpenWRT is not the only project using it, I am aware of at least 2 other Open Source: DD-WRT, McDebian, that use this driver and quiet a few private projects. You want to force everybody to update kernel to 5.4 or patch?

OpenWRT with it backports could patch the code in all, master and other branches, since it is one of the rear use cases with backports.

I was never proposing to patch backports, but what backports project is - the gigantic collection patches to run Wi-Fi stack from newer kernel on older one. And these patches change often, with kernel point releases. You probably noticed that OpenWRT update kernel every week, but sometimes that pattern pauses, this happens when kernel changes require backports change.

**Comment by jeolives** [comment]
I don't want to force anybody to update to 5.3 or later which is why I've closed this PR. 

In the end, I've just hacked around around it in my PR in OpenWrt. 

Am I correct in understanding that your suggestion is to go upstream/patch the backports such that this new vendor policy gets disabled when it is running in as a module in an older Linux kernel?

**Comment by borkra** [comment]
> Am I correct in understanding that your suggestion is to go upstream/patch the backports such that this new vendor policy gets disabled when it is running in as a module in an older Linux kernel?

I was proposing to leave code as is now.

Adding mwlwifi to backports would be perfect, but since it's not part of main kernel nobody will do that.

**Comment by lucenera** [comment]
To understand, to continue updating master do I have to continue using your patch @jeolives ?  Will the patch no longer be needed when OpenWrt is on 5.3?

**Comment by borkra** [comment]
My patch in OpenWRT needs to change, to compile latest mwlwifi code.

Correct once OpenWRT mvebu kernel transitions to 5.4, patch will be no longer needed.

**Comment by lucenera** [comment]
[Correct once OpenWRT mvebu kernel transitions to 5.4, patch will be no longer needed.]
Next year? Maybe.

**Comment by lucenera** [comment]
> My patch in OpenWRT tree needs to change, to compile latest mwlwifi code.
> 
> Correct once OpenWRT mvebu kernel transitions to 5.4, patch will be no longer needed.
Next year? Maybe.

**Comment by borkra** [comment]
This year, I hope. Update is being worked on, at least the core part. You can see commits in developer tree for the OpenWRT core packages, once this is done somebody will port mvebu.

**Comment by lucenera** [comment]
For now with extensive tests, on stock and OpenWrt gain about 100 Mb/s on 5GHz in download.  So I will gladly continue patching them manually as long as necessary.  I have a 1000 Mb/s GPON line.  I can appreciate the difference. Thanks for your wonderful contributions.

**Pull request closed without merging**
