### PR TITLE
@tiremeat 's spinlock changes

### PR DESCRIPTION
**Pull request by notnyt**
Please evaluate these changes from @tiremeat.  sirq usage has dropped significantly and I have not seen any stability issues.

### CODE REVIEW

**Comment by yuhhaurlin** [comment]
rx_desc spin lock is used to protect receive descriptor structure.

**Comment by notnyt** [comment]
@yuhhaurlin Isn't the rx_desc spin lock still used where necessary with this patch?  I'm running with it now with no adverse affects.

**Comment by TireMeat** [comment]
there are a few more spin locks like the one in rx that i believe are worth looking into (this is what I'm doing now).   particularly the functions i'm looking at that have very "generous" locks = mwl_tx_do_amsdu, mwl_tx_flush_amsdu, mwl_tx_skbs, and mwl_tx_done.   fwcmd.c and isr.c are nice and tight.

generally speaking, locks that have loops or external function calls in between (like below pseudo code) are very bad from a performance standpoint.   it is true that more stability arises if structures are locked, but too much locking has other consequences (context switches and general thrashing) 

```
lock 
        for, while, walking a list, and any other loop ...
        some mwl_function_call ...
        end loop
unlock
```

**Comment by yuhhaurlin** [comment]
Your previous modification for receiving does not protect rx descriptor correctly. The reason that the modification did not trigger problem is that this lock is unnecessary.

**Pull request closed without merging**
