### PR TITLE
Remove mwl_tx_descriptor_dump()

### PR DESCRIPTION
**Pull request by mmilburn**
Hi Imre, this is something of a test commit.  If it isn't already obvious, I'd like to help do some cleanup of the code.  I don't get the sense that Marvell is really open to the idea, but I could at least help with little things like issue #9 . 
--original commit message--
This is ostensibly dead code.  It either needs to be removed, or refactored
such that it does not need commenting out.

### CODE REVIEW

**Comment by Stonie** [comment]
Any news from Marvell? 

PS: I wouldn't have thought it too tough to merge new tarballs? (ok so its not ideal, but not a major problem is it?)

**Comment by raven-au** [comment]
A tarball, it's painful and problematic.

You really want the individual commits that resolve problems of add function so you can see history.
That itself can be useful when trying to find problems and not only ones that are related to the changes.

But I doubt Marvel really cares about us.

**Comment by Stonie** [comment]
@raven-au yes, I understand that a tarball is not a git repo. but its better than nothing.  

Who is the contact at Marvel? can we get them to commit here? or at least ship us a regular tarball? I don't mind following up with them if someone can give me a contact?

**Comment by raven-au** [comment]
I believe that David Lin is the community contact.

See the original announcement:
https://lists.openwrt.org/pipermail/openwrt-devel/2014-December/030229.html

I asked a couple of questions in reply to that message and he replied saying he's the community contact but can't find that message now.

**Comment by yuhhaurlin** [comment]
The code had already removed.

**Pull request closed without merging**
